[package]
name = "algorithms"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
rusty-hook = "^0.11.2"

[[bin]]
name = "1_two_sum"
path = "src/arrays/1_two_sum/main.rs"

[[bin]]
name = "2_best_time_to_buy_sell_stock"
path = "src/arrays/2_best_time_to_buy_sell_stock/main.rs"